"""Migration

Revision ID: 050b75416439
Revises: b1750c9f03a5
Create Date: 2023-02-11 22:47:11.628699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050b75416439'
down_revision = 'b1750c9f03a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'about',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'address_street',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'img_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'img_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'address_street',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'about',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
