"""Migration

Revision ID: 0c5383b8fdc7
Revises: d15ef56b286d
Create Date: 2023-02-11 23:33:37.589487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c5383b8fdc7'
down_revision = 'd15ef56b286d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'end_datetime',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('packages', 'img_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('packages', 'price',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'pay_rate',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pay_rate',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('packages', 'price',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('packages', 'img_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'end_datetime',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
