"""Invoice items on Event

Revision ID: 5cedb5446b05
Revises: 6121f573ca81
Create Date: 2022-10-17 22:12:48.972322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cedb5446b05'
down_revision = '6121f573ca81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('invoice_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'invoice_items')
    # ### end Alembic commands ###
