"""Fix

Revision ID: 6121f573ca81
Revises: 750dfbd30a24
Create Date: 2022-10-05 17:51:25.002841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6121f573ca81'
down_revision = '750dfbd30a24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
