"""Fix

Revision ID: 750dfbd30a24
Revises: 
Create Date: 2022-10-05 17:51:03.205418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750dfbd30a24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
