"""Prodfix

Revision ID: 80ab987944cb
Revises: 
Create Date: 2022-10-19 09:32:52.991790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80ab987944cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resourcefolders')
    op.add_column('events', sa.Column('invoice_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'invoice_items')
    op.create_table('resourcefolders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_modified', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('parent_resourcefolder_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='resourcefolders_company_id_fkey'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='resourcefolders_event_id_fkey'),
    sa.ForeignKeyConstraint(['parent_resourcefolder_id'], ['resourcefolders.id'], name='resourcefolders_parent_resourcefolder_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='resourcefolders_pkey')
    )
    # ### end Alembic commands ###
