# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Clockin(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, clockin_time=None, clockout_time=None):  # noqa: E501
        """Clockin - a model defined in OpenAPI

        :param clockin_time: The clockin_time of this Clockin.  # noqa: E501
        :type clockin_time: object
        :param clockout_time: The clockout_time of this Clockin.  # noqa: E501
        :type clockout_time: object
        """
        self.openapi_types = {
            'clockin_time': object,
            'clockout_time': object
        }

        self.attribute_map = {
            'clockin_time': 'clockin_time',
            'clockout_time': 'clockout_time'
        }

        self.clockin_time = clockin_time
        self.clockout_time = clockout_time

    @classmethod
    def from_dict(cls, dikt) -> 'Clockin':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Clockin of this Clockin.  # noqa: E501
        :rtype: Clockin
        """
        return util.deserialize_model(dikt, cls)

    @property
    def clockin_time(self):
        """Gets the clockin_time of this Clockin.


        :return: The clockin_time of this Clockin.
        :rtype: object
        """
        return self._clockin_time

    @clockin_time.setter
    def clockin_time(self, clockin_time):
        """Sets the clockin_time of this Clockin.


        :param clockin_time: The clockin_time of this Clockin.
        :type clockin_time: object
        """
        if clockin_time is None:
            raise ValueError("Invalid value for `clockin_time`, must not be `None`")  # noqa: E501

        self._clockin_time = clockin_time

    @property
    def clockout_time(self):
        """Gets the clockout_time of this Clockin.


        :return: The clockout_time of this Clockin.
        :rtype: object
        """
        return self._clockout_time

    @clockout_time.setter
    def clockout_time(self, clockout_time):
        """Sets the clockout_time of this Clockin.


        :param clockout_time: The clockout_time of this Clockin.
        :type clockout_time: object
        """

        self._clockout_time = clockout_time
