# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.company import Company
from openapi_server import util

from openapi_server.models.company import Company  # noqa: E501

class CompanyListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, companies=None):  # noqa: E501
        """CompanyListResponse - a model defined in OpenAPI

        :param companies: The companies of this CompanyListResponse.  # noqa: E501
        :type companies: List[Company]
        """
        self.openapi_types = {
            'companies': List[Company]
        }

        self.attribute_map = {
            'companies': 'companies'
        }

        self.companies = companies

    @classmethod
    def from_dict(cls, dikt) -> 'CompanyListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CompanyListResponse of this CompanyListResponse.  # noqa: E501
        :rtype: CompanyListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def companies(self):
        """Gets the companies of this CompanyListResponse.


        :return: The companies of this CompanyListResponse.
        :rtype: List[Company]
        """
        return self._companies

    @companies.setter
    def companies(self, companies):
        """Sets the companies of this CompanyListResponse.


        :param companies: The companies of this CompanyListResponse.
        :type companies: List[Company]
        """

        self._companies = companies
