# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.event import Event
from openapi_server import util

from openapi_server.models.event import Event  # noqa: E501

class EventListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, events=None):  # noqa: E501
        """EventListResponse - a model defined in OpenAPI

        :param events: The events of this EventListResponse.  # noqa: E501
        :type events: List[Event]
        """
        self.openapi_types = {
            'events': List[Event]
        }

        self.attribute_map = {
            'events': 'events'
        }

        self.events = events

    @classmethod
    def from_dict(cls, dikt) -> 'EventListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EventListResponse of this EventListResponse.  # noqa: E501
        :rtype: EventListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def events(self):
        """Gets the events of this EventListResponse.


        :return: The events of this EventListResponse.
        :rtype: List[Event]
        """
        return self._events

    @events.setter
    def events(self, events):
        """Sets the events of this EventListResponse.


        :param events: The events of this EventListResponse.
        :type events: List[Event]
        """
        if events is None:
            raise ValueError("Invalid value for `events`, must not be `None`")  # noqa: E501

        self._events = events
