# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.package import Package
from openapi_server import util

from openapi_server.models.package import Package  # noqa: E501

class PackageListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, packages=None):  # noqa: E501
        """PackageListResponse - a model defined in OpenAPI

        :param packages: The packages of this PackageListResponse.  # noqa: E501
        :type packages: List[Package]
        """
        self.openapi_types = {
            'packages': List[Package]
        }

        self.attribute_map = {
            'packages': 'packages'
        }

        self.packages = packages

    @classmethod
    def from_dict(cls, dikt) -> 'PackageListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PackageListResponse of this PackageListResponse.  # noqa: E501
        :rtype: PackageListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def packages(self):
        """Gets the packages of this PackageListResponse.


        :return: The packages of this PackageListResponse.
        :rtype: List[Package]
        """
        return self._packages

    @packages.setter
    def packages(self, packages):
        """Sets the packages of this PackageListResponse.


        :param packages: The packages of this PackageListResponse.
        :type packages: List[Package]
        """

        self._packages = packages
