# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Role(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, description=None, permissions=None):  # noqa: E501
        """Role - a model defined in OpenAPI

        :param id: The id of this Role.  # noqa: E501
        :type id: int
        :param name: The name of this Role.  # noqa: E501
        :type name: str
        :param description: The description of this Role.  # noqa: E501
        :type description: str
        :param permissions: The permissions of this Role.  # noqa: E501
        :type permissions: str
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'description': str,
            'permissions': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'permissions': 'permissions'
        }

        self.id = id
        self.name = name
        self.description = description
        self.permissions = permissions

    @classmethod
    def from_dict(cls, dikt) -> 'Role':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Role of this Role.  # noqa: E501
        :rtype: Role
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Role.

        The identifier for the role.  # noqa: E501

        :return: The id of this Role.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Role.

        The identifier for the role.  # noqa: E501

        :param id: The id of this Role.
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Role.

        name  # noqa: E501

        :return: The name of this Role.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Role.

        name  # noqa: E501

        :param name: The name of this Role.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this Role.

        Block of text describing the role.  # noqa: E501

        :return: The description of this Role.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Role.

        Block of text describing the role.  # noqa: E501

        :param description: The description of this Role.
        :type description: str
        """

        self._description = description

    @property
    def permissions(self):
        """Gets the permissions of this Role.

        Permissions for role  # noqa: E501

        :return: The permissions of this Role.
        :rtype: str
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this Role.

        Permissions for role  # noqa: E501

        :param permissions: The permissions of this Role.
        :type permissions: str
        """
        if permissions is None:
            raise ValueError("Invalid value for `permissions`, must not be `None`")  # noqa: E501

        self._permissions = permissions
