# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.user_validation import UserValidation
from openapi_server import util

from openapi_server.models.user_validation import UserValidation  # noqa: E501

class UserValidationList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, employee_validations=None):  # noqa: E501
        """UserValidationList - a model defined in OpenAPI

        :param employee_validations: The employee_validations of this UserValidationList.  # noqa: E501
        :type employee_validations: List[UserValidation]
        """
        self.openapi_types = {
            'employee_validations': List[UserValidation]
        }

        self.attribute_map = {
            'employee_validations': 'employee_validations'
        }

        self.employee_validations = employee_validations

    @classmethod
    def from_dict(cls, dikt) -> 'UserValidationList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserValidationList of this UserValidationList.  # noqa: E501
        :rtype: UserValidationList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def employee_validations(self):
        """Gets the employee_validations of this UserValidationList.


        :return: The employee_validations of this UserValidationList.
        :rtype: List[UserValidation]
        """
        return self._employee_validations

    @employee_validations.setter
    def employee_validations(self, employee_validations):
        """Sets the employee_validations of this UserValidationList.


        :param employee_validations: The employee_validations of this UserValidationList.
        :type employee_validations: List[UserValidation]
        """
        if employee_validations is None:
            raise ValueError("Invalid value for `employee_validations`, must not be `None`")  # noqa: E501

        self._employee_validations = employee_validations
