# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class User(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, email=None, first_name=None, last_name=None, pay_rate=None, department_id=None, role_id=None):  # noqa: E501
        """User - a model defined in OpenAPI

        :param id: The id of this User.  # noqa: E501
        :type id: int
        :param email: The email of this User.  # noqa: E501
        :type email: str
        :param first_name: The first_name of this User.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this User.  # noqa: E501
        :type last_name: str
        :param pay_rate: The pay_rate of this User.  # noqa: E501
        :type pay_rate: float
        :param department_id: The department_id of this User.  # noqa: E501
        :type department_id: int
        :param role_id: The role_id of this User.  # noqa: E501
        :type role_id: int
        """
        self.openapi_types = {
            'id': int,
            'email': str,
            'first_name': str,
            'last_name': str,
            'pay_rate': float,
            'department_id': int,
            'role_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'email': 'email',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'pay_rate': 'pay_rate',
            'department_id': 'department_id',
            'role_id': 'role_id'
        }

        self.id = id
        self.email = email
        self.first_name = first_name
        self.last_name = last_name
        self.pay_rate = pay_rate
        self.department_id = department_id
        self.role_id = role_id

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this User.

        A unique identifier for a user.  # noqa: E501

        :return: The id of this User.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this User.

        A unique identifier for a user.  # noqa: E501

        :param id: The id of this User.
        :type id: int
        """

        self._id = id

    @property
    def email(self):
        """Gets the email of this User.

        email  # noqa: E501

        :return: The email of this User.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this User.

        email  # noqa: E501

        :param email: The email of this User.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def first_name(self):
        """Gets the first_name of this User.

        The user's first name.  # noqa: E501

        :return: The first_name of this User.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this User.

        The user's first name.  # noqa: E501

        :param first_name: The first_name of this User.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this User.

        The user's last name.  # noqa: E501

        :return: The last_name of this User.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this User.

        The user's last name.  # noqa: E501

        :param last_name: The last_name of this User.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def pay_rate(self):
        """Gets the pay_rate of this User.

        The user's pay rate.  # noqa: E501

        :return: The pay_rate of this User.
        :rtype: float
        """
        return self._pay_rate

    @pay_rate.setter
    def pay_rate(self, pay_rate):
        """Sets the pay_rate of this User.

        The user's pay rate.  # noqa: E501

        :param pay_rate: The pay_rate of this User.
        :type pay_rate: float
        """

        self._pay_rate = pay_rate

    @property
    def department_id(self):
        """Gets the department_id of this User.

        The user's department id.  # noqa: E501

        :return: The department_id of this User.
        :rtype: int
        """
        return self._department_id

    @department_id.setter
    def department_id(self, department_id):
        """Sets the department_id of this User.

        The user's department id.  # noqa: E501

        :param department_id: The department_id of this User.
        :type department_id: int
        """

        self._department_id = department_id

    @property
    def role_id(self):
        """Gets the role_id of this User.

        The user's role id.  # noqa: E501

        :return: The role_id of this User.
        :rtype: int
        """
        return self._role_id

    @role_id.setter
    def role_id(self, role_id):
        """Sets the role_id of this User.

        The user's role id.  # noqa: E501

        :param role_id: The role_id of this User.
        :type role_id: int
        """

        self._role_id = role_id
